NUMPY CODES FOR DATA ANALYSIS 

Numpy is a python package that stands for numerical python
it is the core library for scientific computing which contains a powerful n- dimensional array object.



import library "numpy"

In [16]:
import numpy as np 

In [17]:
l= [12,23,34,45,56,56]
l

[12, 23, 34, 45, 56, 56]

Display the type of an object 

In [18]:
type(l)


list

In [19]:
A=np.array(l)
A


array([12, 23, 34, 45, 56, 56])

In [20]:
type(A)

numpy.ndarray

In [6]:
A.data

In [7]:
A.dtype

dtype('int32')

In [8]:
A=A.astype(float)


In [9]:
A

array([12., 23., 34., 45., 56., 56.])

In [10]:
A.dtype

dtype('float64')

Generate equal spaced number between 0 to 20 

In [11]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Generate  number between 0 to 20 with a space of 2

In [12]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Generate  number between 0 to 20 with a space of 5

In [13]:
B=np.arange(0,21,5)
B

array([ 0,  5, 10, 15, 20])

To get Shape,size,dimension,bytesize

In [21]:
B.shape

(5,)

In [22]:
B.size

5

In [23]:
B.ndim

1

In [25]:
B.itemsize # bytes consumed by an element of an array object 

4

In [26]:
B.nbytes # bytes consumed by an array object 

20

In [27]:
len(B)# length of array

5

In [28]:
np.zeros(12) # array of zeroes repeating 12 times 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones(12) # array of ones repeating 12 times 


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# for repeat 5 ,four times in an array: repeat(m,n);m will be repeated n times 

In [30]:
#repeat each element in an array five times 
C=np.array([12,23,34])
np.repeat(C,5)


array([12, 12, 12, 12, 12, 23, 23, 23, 23, 23, 34, 34, 34, 34, 34])

In [31]:
# generate 5 , 8 times 
np.full(5,8)

array([8, 8, 8, 8, 8])

In [32]:
# generate even numbers between 1 and 100
Even=np.arange(1,100)
Even[Even%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [33]:
# generate odd numbers between 1 and 100
Odd=np.arange(1,100)
Odd[Odd%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

# automatically generates values between m and n givingequal spacingand  k numbers between them 
#  np.linspace(m,n,k)

In [34]:

np.linspace(10,25,6)


array([10., 13., 16., 19., 22., 25.])

In [35]:
#np.random.random(n)
np.random.random(5)

array([0.04719643, 0.51447628, 0.71438694, 0.2441689 , 0.99325916])

In [36]:
# random numbers between 5 and 10 randomly and there will 8 decimal numbers 
RANDOM=np.random.uniform(5,10,8)
RANDOM

array([9.01910723, 6.30843503, 5.78034062, 5.32091389, 5.7192093 ,
       9.38648941, 7.68450523, 9.28616074])

In [37]:
# random integers numbers between 1 and 100 and there will 10 numbers 
np.random.randint(0,100,10)

array([42, 57, 97, 99, 75, 30, 47, 16, 75, 76])

Two methods to remove the decimal place

In [38]:
np.floor(RANDOM)

array([9., 6., 5., 5., 5., 9., 7., 9.])

In [39]:
np.trunc(RANDOM)

array([9., 6., 5., 5., 5., 9., 7., 9.])

In [40]:
print(np.__version__)

1.20.3


In [41]:
List1=np.array([12,23,34,45,56])
print(List1)
print(type(List1))


[12 23 34 45 56]
<class 'numpy.ndarray'>


In [42]:
Tup1=np.array((12,23,34,45,56))
print(Tup1)
print(type(Tup1))

[12 23 34 45 56]
<class 'numpy.ndarray'>


# Dimensions 

In [43]:

zero_D_array=np.array(67)
zero_D_array


array(67)

In [44]:
# to remove 'array' from the output 
print(zero_D_array)
# to know the type of array
zero_D_array.ndim

67


0

In [45]:
one_array=np.array([34,45,6,56])
one_array

array([34, 45,  6, 56])

In [48]:
# to remove 'array' from the output 
print(one_array)
# to know the type of array
print(type(one_array))
one_array.ndim

[34 45  6 56]
<class 'numpy.ndarray'>


1

In [49]:
two_array=np.array([[34,45],[6,56],[4,65]])
two_array


array([[34, 45],
       [ 6, 56],
       [ 4, 65]])

In [50]:
print(two_array)
print(type(two_array))
two_array.ndim

[[34 45]
 [ 6 56]
 [ 4 65]]
<class 'numpy.ndarray'>


2

In [51]:
a=[34,45]
b=[6,56]
c=[4,65]
two_D=np.array([a,b,c])
print(two_D)

[[34 45]
 [ 6 56]
 [ 4 65]]


In [52]:
a=['a','d']
b=['f','s']
c=[4,65]
two_D_str=np.array([a,b,c])
print(two_D_str)

[['a' 'd']
 ['f' 's']
 ['4' '65']]


In [53]:
three_array=np.array([[34,45],[6,56],[4,65],[56,6],[5,4]])
three_array

array([[34, 45],
       [ 6, 56],
       [ 4, 65],
       [56,  6],
       [ 5,  4]])

In [54]:
three_array.ndim

2

In [55]:
a1=np.array([11,34,56,78,89])
a1


array([11, 34, 56, 78, 89])

In [56]:
print(a1[0])

11


In [57]:
A=print(a1[1])

B=print(a1[3])


34
78


In [58]:
print(a1[1]+a1[3])

112


In [59]:
print(a1[1]-a1[3])

-44


In [60]:
print(a1[1]*a1[3])

2652


In [61]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
print(a2[0,1]) # first row second column

2


In [63]:
print(a2[1,1],a2[0,2]) # any two elements from the matrix

7 3


In [64]:
print(a2[1,-1]) # element from last row and last column 

10


In [65]:
a1

array([11, 34, 56, 78, 89])

In [66]:
print(a1[-4:-1])

[34 56 78]


In [67]:
print(a1[:-1])

[11 34 56 78]


In [68]:
print(a1[0:5:2]) # getting values with 

[11 56 89]


In [69]:
print(a1[0:4:2])

[11 56]


In [70]:
print(a1[::2])

[11 56 89]


In [71]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [72]:
print(a2[0,0:3])

[1 2 3]


In [73]:
a1

array([11, 34, 56, 78, 89])

In [74]:
ast=np.array(["deep","ash"])
print(ast.dtype)

<U4


In [75]:
print(a1.dtype)

int32


In [76]:
arr=np.array([1,256,31,4098],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'256' b'31' b'4098']
|S4


In [77]:
arr=np.array(['1','2','3','4'])
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


In [78]:
arr=np.array(['1','2','3','4'],dtype='i4')
print(arr)

[1 2 3 4]


In [79]:
ar=np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
ar.sum()

45

In [81]:
ar.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [82]:
np.cumsum(ar)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [83]:
print(np.cumsum(ar))

[ 0  1  3  6 10 15 21 28 36 45]


In [84]:
ar.min()

0

In [85]:
ar.max()

9

In [86]:
ar.mean()

4.5

In [88]:
np.median(ar)

4.5

In [91]:
ar=np.array([78,89,54,12,79,65])
ar

array([78, 89, 54, 12, 79, 65])

In [92]:
ar.argmin()

3

In [93]:
ar.argmax()

1

In [94]:
np.var(ar)

640.4722222222222

In [95]:
np.std(ar)

25.307552671529148

In [96]:
np.percentile(ar,75)

78.75

In [97]:
np.percentile(ar,25)

56.75

In [98]:
np.percentile(ar,50)

71.5

In [99]:
np.percentile(ar,60)


78.0

In [102]:
female_score=np.array([78,89,54,12,79,65])
female_score

array([78, 89, 54, 12, 79, 65])

In [103]:
male_score=np.array([56,90,64,22,59,85])
male_score

array([56, 90, 64, 22, 59, 85])

In [104]:
np.cov(female_score,male_score) # covariance matrix 

array([[768.56666667, 531.73333333],
       [531.73333333, 591.86666667]])

In [108]:
np.corrcoef(female_score,male_score) # corelation coefficient 

array([[1.        , 0.78839012],
       [0.78839012, 1.        ]])

In [109]:
np.quantile(female_score,[0.25,0.75]) # quantiles 

array([56.75, 78.75])

In [110]:
score=np.array([56,90,64,22,59,85])  
y=score.copy()
score[3]=89
print('score=',score)
print('copy=',y)


score= [56 90 64 89 59 85]
copy= [56 90 64 22 59 85]


In [111]:
score=np.array([56,90,64,22,59,85])  
y=score.view()
score[3]=89
print('score=',score)
print('view=',y)


score= [56 90 64 89 59 85]
view= [56 90 64 89 59 85]


copy is a new array and view is just the original array 

In [112]:
score=np.array([56,90,64,22,59,85]) 
y=score.view()
x=score.copy()
print(x.base)
print(y.base)

None
[56 90 64 22 59 85]


In [115]:
n=score.reshape(2,3) #to reshape any array from 1d to 2d of rows and col

iterating array


In [114]:
for i in score:
    print(i)

56
90
64
22
59
85


In [116]:
for i in n:
    print(i)

[56 90 64]
[22 59 85]


In [117]:
for i in n:
    for j in i:
        print(j)

56
90
64
22
59
85


join two arrays 

In [153]:
m=np.array([78,89,54,12,79,65])
m

array([78, 89, 54, 12, 79, 65])

In [154]:
n=np.array([56,90,64,22,59,85]) 
n

array([56, 90, 64, 22, 59, 85])

In [155]:
#join using stack function 
joined=np.stack((m,n),axis=1)
joined

array([[78, 56],
       [89, 90],
       [54, 64],
       [12, 22],
       [79, 59],
       [65, 85]])

In [156]:
joined=np.stack((m,n),axis=0)
joined

array([[78, 89, 54, 12, 79, 65],
       [56, 90, 64, 22, 59, 85]])

In [157]:
# hstack()
horizontalstack=np.hstack((m,n))
horizontalstack

array([78, 89, 54, 12, 79, 65, 56, 90, 64, 22, 59, 85])

In [158]:
#dstack()
verticalstack=np.vstack((m,n))
verticalstack

array([[78, 89, 54, 12, 79, 65],
       [56, 90, 64, 22, 59, 85]])

In [159]:
#dstack(): to stack along height which is the same as depth
verticalstack=np.dstack((m,n))
verticalstack

array([[[78, 56],
        [89, 90],
        [54, 64],
        [12, 22],
        [79, 59],
        [65, 85]]])

In [160]:
# to split array in to parts
n1=np.array_split(n,3) 
print(n1)

[array([56, 90]), array([64, 22]), array([59, 85])]


In [161]:
n2= np.array([[56, 90],[64, 22],[59, 85]])
n2

array([[56, 90],
       [64, 22],
       [59, 85]])

In [162]:
n3=np.array_split(n2,2)
print(n3)

[array([[56, 90],
       [64, 22]]), array([[59, 85]])]


In [163]:
print(n3[0])

[[56 90]
 [64 22]]


In [164]:
#hsplit()
ar=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.hsplit(ar,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [165]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.vsplit(ar,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [166]:
ar=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]) # double brackets for the array
np.dsplit(ar,3)

[array([[[ 1],
         [ 4],
         [ 7],
         [10]]]),
 array([[[ 2],
         [ 5],
         [ 8],
         [11]]]),
 array([[[ 3],
         [ 6],
         [ 9],
         [12]]])]

In [167]:
# searching an array 
ar=np.array([34,45,6,5,4,32,45])
np.where(ar==45)


(array([1, 6], dtype=int64),)

In [168]:
ar=np.array([34,45,6,5,4,32,45])
np.where(ar==5)

(array([3], dtype=int64),)

In [169]:
# replace elements in an array 
ar= np.arange(1,21)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [170]:
rep=np.where(ar%2==0,0,ar) # replaces all even numbers by 0
rep

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0])

In [171]:
# missing value in an array
a=np.array([1,np.nan,34,np.nan,67,5])
a

array([ 1., nan, 34., nan, 67.,  5.])

In [172]:
np.isnan(a)

array([False,  True, False,  True, False, False])

In [173]:
a[np.isnan(a)]=65
a

array([ 1., 65., 34., 65., 67.,  5.])

In [174]:
np.isnan(a).any() # to check null value 

False

In [176]:
np.intersect1d(m,n)# to find common elements 

array([], dtype=int32)

In [177]:
a=np.array([2,4,5,6,7,8,4])
b=np.array([2,4,3,6,34,18,14])
np.intersect1d(a,b)

array([2, 4, 6])

In [178]:
a

array([2, 4, 5, 6, 7, 8, 4])

In [179]:
b

array([ 2,  4,  3,  6, 34, 18, 14])

In [180]:
np.setdiff1d(a,b) # elements in a but not in b (a-b)


array([5, 7, 8])

In [181]:
np.setdiff1d(b,a) # elements in b but not in a(b-a)

array([ 3, 14, 18, 34])

checking elements using isin()

In [183]:
np.isin(a,[4,34]) # to check 4 and 34 in a , will return true if exist

array([False,  True, False, False, False, False,  True])

In [184]:
np.flip(a) # to reverse an array 

array([4, 8, 7, 6, 5, 4, 2])

In [185]:
np.sort(a) # to sort an array 

array([2, 4, 4, 5, 6, 7, 8])

# OPERATION ON 2D 

In [189]:
A=np.array([[23,34,5],[23,3,4],[3,4,1]])
A

array([[23, 34,  5],
       [23,  3,  4],
       [ 3,  4,  1]])

In [190]:
np.amin(A,axis=0)

array([3, 3, 1])

In [191]:
np.amin(A,axis=1)

array([5, 3, 1])

In [195]:
np.amax(A,axis=0)

array([23, 34,  5])

In [196]:
np.amax(A,axis=1)

array([34, 23,  4])