PANDAS 

In [1]:
import pandas as pd
import numpy as np
import warnings 


In [89]:
print(pd.__version__)

1.3.4


In [90]:
a=pd.Series()
a

C:\Users\Tanuja\AppData\Local\Temp/ipykernel_2156/454184989.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  a=pd.Series()


Series([], dtype: float64)

In [4]:
a=np.array([11,21,13,12,13])
v=pd.Series(a)
v

0    11
1    21
2    13
3    12
4    13
dtype: int32

In [5]:
type(a)


numpy.ndarray

In [6]:
type(v)

pandas.core.series.Series

In [7]:
s= pd.Series([1,2,3],index=['a','b','c'])
s

a    1
b    2
c    3
dtype: int64

In [8]:
s= pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [9]:
s.index=['a','b','c']

In [10]:
v1=np.random.random(12)
v1

array([0.37642   , 0.89400981, 0.87278298, 0.01883237, 0.77517082,
       0.59096725, 0.94285827, 0.38418484, 0.61537855, 0.75754103,
       0.90827698, 0.39972577])

In [11]:
v2=np.arange(2,14)
v2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [12]:
d={'a':10,'b':20,'c':30,'d':40} # series from dictionary
s1=pd.Series(d)
s1

a    10
b    20
c    30
d    40
dtype: int64

In [13]:
pd.Series(34,index=[10,11,12,13]) # series from scalar

10    34
11    34
12    34
13    34
dtype: int64

In [14]:
pd.Series(45)

0    45
dtype: int64

In [15]:
a= np.array([10,22,31,42,55,36,47])
v=pd.Series(a,index=['a','b','c','d','e','f','g'])
v

a    10
b    22
c    31
d    42
e    55
f    36
g    47
dtype: int32

In [16]:
v.dtype


dtype('int32')

In [17]:
v.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [18]:
v.shape

(7,)

In [19]:
v.size

7

In [20]:
v.ndim

1

In [21]:
v.nbytes

28

In [22]:
v.hasnans # to check null values if null then false

False

In [23]:
v.empty

False

In [24]:
v.values  #just the values 

array([10, 22, 31, 42, 55, 36, 47])

In [25]:
v # here both index and values will come 

a    10
b    22
c    31
d    42
e    55
f    36
g    47
dtype: int32

In [26]:
v.value_counts() # to check the counts of each element in array 

10    1
22    1
31    1
42    1
55    1
36    1
47    1
dtype: int64

In [27]:
a=pd.Series([1,2,3,4,1,3,3,4,1,3,4,1,3,4])
a.value_counts()

3    5
1    4
4    4
2    1
dtype: int64

# Operations in series:

In [38]:
import pandas as pd

data = [[10, 18, 11], [13, 15, 8], [9, 20, 3]]

df = pd.DataFrame(data)

print(df.sum())
print(df.sub())
print(df.mul())
print(df.div())

0    32
1    53
2    22
dtype: int64


TypeError: f() missing 1 required positional argument: 'other'

In [35]:
s1.max()

AttributeError: 'list' object has no attribute 'max'

In [39]:
# creating a empty dataframe

a=pd.DataFrame()
print(a)

Empty DataFrame
Columns: []
Index: []


In [44]:
# create dataframe from list

list=(["divya","hiteesh","pavani","sushmitha"])
d=pd.DataFrame(list)
d

0
0      divya
1    hiteesh
2     pavani
3  sushmitha

In [45]:
# add columns is dataframe

marks=[95,85,73,81]
d[1]=marks
d

0   1
0      divya  95
1    hiteesh  85
2     pavani  73
3  sushmitha  81

In [46]:
# give name to columns

d.columns=["name","marks"]
d

name  marks
0      divya     95
1    hiteesh     85
2     pavani     73
3  sushmitha     81

In [47]:
# create dataframe from dict

d1=pd.DataFrame({"ID":[1,2,3,4],"NAME":["Akhil","Ashish","Ajay","Arun"]})
d1

ID    NAME
0   1   Akhil
1   2  Ashish
2   3    Ajay
3   4    Arun

In [55]:
# create dataframe from random values

r=np.random.random((5,5))
r

array([[0.02004917, 0.62974715, 0.61135775, 0.27958691, 0.24487157],
       [0.20638781, 0.8314748 , 0.43858457, 0.37072738, 0.26534535],
       [0.85601501, 0.24851027, 0.79869305, 0.66795188, 0.97299321],
       [0.69109054, 0.2627595 , 0.15997254, 0.88409056, 0.74011828],
       [0.40323055, 0.52814053, 0.45415487, 0.38991072, 0.72232943]])

In [56]:
d2=pd.DataFrame(r)
d2

0         1         2         3         4
0  0.020049  0.629747  0.611358  0.279587  0.244872
1  0.206388  0.831475  0.438585  0.370727  0.265345
2  0.856015  0.248510  0.798693  0.667952  0.972993
3  0.691091  0.262759  0.159973  0.884091  0.740118
4  0.403231  0.528141  0.454155  0.389911  0.722329

In [58]:
date1=pd.date_range("today",periods=7)
date1

DatetimeIndex(['2022-02-11 10:23:21.555737', '2022-02-12 10:23:21.555737',
               '2022-02-13 10:23:21.555737', '2022-02-14 10:23:21.555737',
               '2022-02-15 10:23:21.555737', '2022-02-16 10:23:21.555737',
               '2022-02-17 10:23:21.555737'],
              dtype='datetime64[ns]', freq='D')

In [68]:
date2=pd.date_range(start="2022-05-21",end="2022-05-25")
date2

DatetimeIndex(['2022-05-21', '2022-05-22', '2022-05-23', '2022-05-24',
               '2022-05-25'],
              dtype='datetime64[ns]', freq='D')

In [71]:
date3=pd.date_range(start="2022-05-21",periods=5)
date3

DatetimeIndex(['2022-05-21', '2022-05-22', '2022-05-23', '2022-05-24',
               '2022-05-25'],
              dtype='datetime64[ns]', freq='D')

In [69]:
d2=pd.DataFrame(r)
d2

0         1         2         3         4
0  0.020049  0.629747  0.611358  0.279587  0.244872
1  0.206388  0.831475  0.438585  0.370727  0.265345
2  0.856015  0.248510  0.798693  0.667952  0.972993
3  0.691091  0.262759  0.159973  0.884091  0.740118
4  0.403231  0.528141  0.454155  0.389911  0.722329

In [72]:
d2=pd.DataFrame(r,date3)
d2

0         1         2         3         4
2022-05-21  0.020049  0.629747  0.611358  0.279587  0.244872
2022-05-22  0.206388  0.831475  0.438585  0.370727  0.265345
2022-05-23  0.856015  0.248510  0.798693  0.667952  0.972993
2022-05-24  0.691091  0.262759  0.159973  0.884091  0.740118
2022-05-25  0.403231  0.528141  0.454155  0.389911  0.722329

In [74]:
# changing the columns names

d2.columns=["A","B","C","D","E"]
d2

A         B         C         D         E
2022-05-21  0.020049  0.629747  0.611358  0.279587  0.244872
2022-05-22  0.206388  0.831475  0.438585  0.370727  0.265345
2022-05-23  0.856015  0.248510  0.798693  0.667952  0.972993
2022-05-24  0.691091  0.262759  0.159973  0.884091  0.740118
2022-05-25  0.403231  0.528141  0.454155  0.389911  0.722329

In [75]:
# list index

d2.index

DatetimeIndex(['2022-05-21', '2022-05-22', '2022-05-23', '2022-05-24',
               '2022-05-25'],
              dtype='datetime64[ns]', freq='D')

In [76]:
# list column names

d2.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [77]:
# datatypes of each column

d2.dtypes

A    float64
B    float64
C    float64
D    float64
E    float64
dtype: object

In [88]:
# sort dataframe by column "A" in ascending order

d2.sort_values(by="A")
d2.sort_values(by="B")
d2.sort_values(by="C")
d2.sort_values(by="D")
d2.sort_values(by="E")

A         B         C         D         E
2022-05-21  0.020049  0.629747  0.611358  0.279587  0.244872
2022-05-22  0.206388  0.831475  0.438585  0.370727  0.265345
2022-05-25  0.403231  0.528141  0.454155  0.389911  0.722329
2022-05-24  0.691091  0.262759  0.159973  0.884091  0.740118
2022-05-23  0.856015  0.248510  0.798693  0.667952  0.972993

In [ ]:
Delete column in dataframe